export const API_KEY = "api_key=2b1fd64cd979487c5f0deddc18cc2dad";
export const URL_MOVIES = "https://api.themoviedb.org/3/movie/popular?";
export const BASE_URL_IMG = "https://image.tmdb.org/t/p/";
export const SIZE_IMAGE = "original";
export const URL_GENRES = "https://api.themoviedb.org/3/genre/movie/list?";
export const URL_LENGUAGE = "language=en-US";
export const URL_BASE = "https://api.themoviedb.org/3/movie/";
export const URL_VIDEO = "/videos?";
export const API_YOUTUBE_URL = "https://www.youtube.com/embed/";
